MAX_RELEVANT_MODELS     = 1000
CLASSIFICATION_THREADS  = 10
MODELS_PER_CLASSIF_PROC = 1000

GENERIC_ILASP_CMD       = ["ILASP", "--version=2i"]
GENERIC_CLINGO_CMD      = ["clingo", "0"]
INVENTED_PREDICATES     = ["invented_pred"]
ILASP_LABEL_STRING      = "gENERIC_LABEL"

PER_MODEL_PREDS         = ["comp"]

NO_LABEL_STRING         = "No label"
MULTIPLE_LABELS_STRING  = "Multiple labels"
